# Set up infrastructure on windows

version: '3.8'

services:
  hmmmm_api:
    container_name: hmmmm_test_api
    image: nt4rever/hmmmm:latest
    env_file: .env
    environment:
      - NODE_ENV=production
    ports:
      - ${PORT}:${PORT}
    restart: unless-stopped
    depends_on:
      - hmmmm_mongodb
      - hmmmm_redis
      - hmmmm_ai

  hmmmm_mongodb:
    container_name: hmmmm_test_mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    expose:
      - ${DATABASE_PORT}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - mongo_db_data:/data/db
    restart: unless-stopped
  hmmmm_redis:
    container_name: hmmmm_test_redis
    image: redis:alpine
    expose:
      - ${REDIS_PORT}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    restart: unless-stopped
  hmmmm_ai:
    env_file: .env
    image: nt4rever/rts:latest
    container_name: hmmmm_test_ai
    ports:
      - 8888:8888
    restart: unless-stopped

networks:
  default:
    driver: bridge
volumes:
  mongo_db_data:
    driver: local
