services:
  hmmmm_api:
    container_name: hmmmm_api
    image: nt4rever/hmmmm:latest
    env_file: .env
    environment:
      - NODE_ENV=production
    ports:
      - ${PORT}:${PORT}
    restart: unless-stopped
  hmmmm_mongodb:
    container_name: ${DATABASE_HOST}
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    expose:
      - ${DATABASE_PORT}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
  hmmmm_redis:
    container_name: ${REDIS_HOST}
    image: redis:alpine
    expose:
      - ${REDIS_PORT}
    # ports:
    #   - ${REDIS_PORT}:${REDIS_PORT}
    restart: unless-stopped
  hmmmm_minio:
    image: "minio/minio:RELEASE.2024-10-13T13-34-11Z"
    ports:
        - "${FORWARD_MINIO_PORT:-9000}:9000"
        - "${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900"
    environment:
        MINIO_ROOT_USER: "${AWS_ACCESS_KEY_ID}"
        MINIO_ROOT_PASSWORD: "${AWS_SECRET_ACCESS_KEY}"
    command: minio server /data --console-address ":8900"
    volumes:
        - "minio_data:/data"
    healthcheck:
        test: ["CMD", "mc", "ready", "local"]
        retries: 3
        timeout: 5s
  hmmmm_mailpit:
    image: 'axllent/mailpit:v1.21.0'
    ports:
        - '${FORWARD_MAILPIT_PORT:-1025}:1025'
        - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    environment:
        - MP_UI_AUTH:${MAIL_USER:-mail}
        - MP_SMTP_AUTH:${MAIL_PASSWORD:-mailpassword}
  hmmmm_ai:
    env_file: .env
    image: nt4rever/rts:latest
    container_name: hmmmm_ai
    ports:
      - 8001:8888
    restart: unless-stopped
networks:
  default:
    driver: bridge
volumes:
  mongo_data:
    driver: local
  minio_data:
    driver: local

